name: playsite1
favicon: null
layout_spectrum: 0.24515
typography_spectrum: 0.83375
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eaecf7'
    - '#dc0251'
    - '#d34b7e'
    - '#030307'
    - '#a0a3a9'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
